<?php
declare(strict_types=1);require __DIR__.'/includes/bootstrap.php';$a=$_GET['action']??'';
if($a==='status'){$u=user();out(['ok'=>true,'authenticated'=>(bool)$u,'user'=>$u,'csrf'=>$u?csrf():null,'appName'=>cfg('app_name'),'aiConfigured'=>(bool)cfg('openai_api_key')]);}
if($a==='login'&&$_SERVER['REQUEST_METHOD']==='POST'){$d=input();$email=strtolower(clean($d['email']??'',200));$pw=(string)($d['password']??'');$found=null;foreach(jr('users.json',[]) as $u)if(strtolower((string)($u['email']??''))===$email&&!empty($u['passwordHash'])&&empty($u['disabled'])){$found=$u;break;}if(!$found||!password_verify($pw,$found['passwordHash'])){usleep(200000);out(['ok'=>false,'error'=>'Email or password is incorrect.'],401);}session_regenerate_id(true);$_SESSION['uid']=$found['id'];$_SESSION['csrf']=bin2hex(random_bytes(24));audit('login');out(['ok'=>true,'user'=>user(),'csrf'=>csrf()]);}
if($a==='media'){auth();$id=clean($_GET['id']??'',100);foreach(jr('media.json',[]) as $m)if(($m['id']??'')===$id){$p=MUSIC63_STORAGE.'/uploads/'.basename($m['stored']);if(!is_file($p))out(['ok'=>false,'error'=>'File not found.'],404);header('Content-Type: '.($m['mime']??'application/octet-stream'));header('Content-Length: '.filesize($p));header('Content-Disposition: inline; filename="'.rawurlencode($m['name']??'file').'"');readfile($p);exit;}out(['ok'=>false,'error'=>'File not found.'],404);}
$me=auth();if($_SERVER['REQUEST_METHOD']!=='GET')check_csrf();
switch($a){
case 'logout':audit('logout');$_SESSION=[];session_destroy();out(['ok'=>true]);
case 'songs':$s=jr('songs.json',[]);usort($s,fn($x,$y)=>strcmp((string)($y['updatedAt']??''),(string)($x['updatedAt']??'')));out(['ok'=>true,'songs'=>$s]);
case 'save_song':$d=input();$song=song_norm(is_array($d['song']??null)?$d['song']:[]);$rows=jr('songs.json',[]);$hit=false;foreach($rows as $i=>$r)if(($r['id']??'')===$song['id']){$song['createdAt']=$r['createdAt']??$song['createdAt'];$rows[$i]=$song;$hit=true;break;}if(!$hit)$rows[]=$song;jw('songs.json',$rows);audit('save_song',['songId'=>$song['id']]);out(['ok'=>true,'song'=>$song]);
case 'delete_song':$id=clean(input()['id']??'',100);jw('songs.json',array_values(array_filter(jr('songs.json',[]),fn($s)=>($s['id']??'')!==$id)));audit('delete_song',['songId'=>$id]);out(['ok'=>true]);
case 'settings':out(['ok'=>true,'settings'=>jr('settings.json',[])]);
case 'save_settings':admin();$d=input();$st=jr('settings.json',[]);foreach(['defaultBpm','defaultKey','sampleLibrary','sourceBookmarks'] as $k)if(isset($d['settings'])&&array_key_exists($k,$d['settings']))$st[$k]=$d['settings'][$k];jw('settings.json',$st);out(['ok'=>true,'settings'=>$st]);
case 'users':admin();out(['ok'=>true,'users'=>array_map(fn($u)=>['id'=>$u['id'],'email'=>$u['email'],'name'=>$u['name']??'','role'=>$u['role']??'user','disabled'=>!empty($u['disabled'])],jr('users.json',[]))]);
case 'save_user':admin();$d=input();$email=strtolower(clean($d['email']??'',200));if(!filter_var($email,FILTER_VALIDATE_EMAIL))out(['ok'=>false,'error'=>'Valid email required.'],422);$rows=jr('users.json',[]);$id=clean($d['id']??'',100)?:uid('usr');$hit=false;foreach($rows as $i=>$u)if(($u['id']??'')===$id){$rows[$i]['email']=$email;$rows[$i]['name']=clean($d['name']??$email,200);$rows[$i]['role']=($d['role']??'')==='admin'?'admin':'user';$rows[$i]['disabled']=!empty($d['disabled']);if(!empty($d['password']))$rows[$i]['passwordHash']=password_hash((string)$d['password'],PASSWORD_DEFAULT);$hit=true;break;}if(!$hit){if(strlen((string)($d['password']??''))<10)out(['ok'=>false,'error'=>'New user password must be at least 10 characters.'],422);$rows[]=['id'=>$id,'email'=>$email,'name'=>clean($d['name']??$email,200),'role'=>($d['role']??'')==='admin'?'admin':'user','disabled'=>false,'passwordHash'=>password_hash((string)$d['password'],PASSWORD_DEFAULT),'createdAt'=>gmdate('c')];}jw('users.json',$rows);out(['ok'=>true]);
case 'change_password':$d=input();$cur=(string)($d['currentPassword']??'');$new=(string)($d['newPassword']??'');if(strlen($new)<10)out(['ok'=>false,'error'=>'New password must be at least 10 characters.'],422);$rows=jr('users.json',[]);foreach($rows as $i=>$u)if(($u['id']??'')===$me['id']){if(!password_verify($cur,(string)$u['passwordHash']))out(['ok'=>false,'error'=>'Current password is incorrect.'],401);$rows[$i]['passwordHash']=password_hash($new,PASSWORD_DEFAULT);$rows[$i]['passwordChangedAt']=gmdate('c');jw('users.json',$rows);audit('change_password');out(['ok'=>true]);}out(['ok'=>false,'error'=>'User not found.'],404);
case 'upload':if(empty($_FILES['file']['tmp_name']))out(['ok'=>false,'error'=>'Choose a file first.'],422);$f=$_FILES['file'];if(($f['size']??0)>(int)cfg('max_upload_bytes'))out(['ok'=>false,'error'=>'File too large.'],413);$name=basename((string)$f['name']);$ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));$allowed=['pdf','mid','midi','musicxml','mxl','xml','mp3','wav','m4a','ogg','flac','png','jpg','jpeg','webp','json'];if(!in_array($ext,$allowed,true))out(['ok'=>false,'error'=>'Unsupported file type.'],415);$id=uid('media');$stored=$id.'.'.$ext;$dest=MUSIC63_STORAGE.'/uploads/'.$stored;if(!move_uploaded_file($f['tmp_name'],$dest))out(['ok'=>false,'error'=>'Upload failed.'],500);$mime=function_exists('mime_content_type')?(mime_content_type($dest)?:'application/octet-stream'):'application/octet-stream';$m=['id'=>$id,'name'=>$name,'stored'=>$stored,'mime'=>$mime,'size'=>(int)$f['size'],'uploadedAt'=>gmdate('c'),'user'=>$me['email']];$rows=jr('media.json',[]);$rows[]=$m;jw('media.json',$rows);out(['ok'=>true,'media'=>$m,'url'=>'api.php?action=media&id='.rawurlencode($id)]);
case 'backup':admin();header('Content-Type: application/json');header('Content-Disposition: attachment; filename="music63-backup-'.gmdate('Ymd-His').'.json"');echo json_encode(['format'=>'music63-backup-v1','exportedAt'=>gmdate('c'),'songs'=>jr('songs.json',[]),'settings'=>jr('settings.json',[]),'media'=>jr('media.json',[])],JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);exit;
case 'restore':admin();$b=input()['backup']??null;if(!is_array($b)||($b['format']??'')!=='music63-backup-v1')out(['ok'=>false,'error'=>'Invalid backup.'],422);if(isset($b['songs']))jw('songs.json',array_values($b['songs']));if(isset($b['settings']))jw('settings.json',$b['settings']);out(['ok'=>true]);
case 'ai_compose':$key=(string)cfg('openai_api_key');if(!$key)out(['ok'=>false,'error'=>'AI is not configured on the server. Offline Smart Composer is available.'],409);$d=input();$prompt=clean($d['prompt']??'',4000);$style=clean($d['style']??'Latvian melodic pop',200);$instruments=is_array($d['instruments']??null)?array_values(array_slice($d['instruments'],0,8)):['Piano','Clarinet Bb'];$bars=max(4,min(16,(int)($d['bars']??8)));$schema=['type'=>'object','properties'=>['title'=>['type'=>'string'],'key'=>['type'=>'string'],'mode'=>['type'=>'string','enum'=>['major','minor']],'bpm'=>['type'=>'integer'],'chords'=>['type'=>'array','items'=>['type'=>'object','properties'=>['bar'=>['type'=>'integer'],'beat'=>['type'=>'number'],'symbol'=>['type'=>'string']],'required'=>['bar','beat','symbol'],'additionalProperties'=>false]],'melody'=>['type'=>'array','items'=>['type'=>'object','properties'=>['bar'=>['type'=>'integer'],'beat'=>['type'=>'number'],'duration'=>['type'=>'number'],'midi'=>['type'=>'integer'],'lyric'=>['type'=>'string']],'required'=>['bar','beat','duration','midi','lyric'],'additionalProperties'=>false]],'arrangementNotes'=>['type'=>'array','items'=>['type'=>'string']]],'required'=>['title','key','mode','bpm','chords','melody','arrangementNotes'],'additionalProperties'=>false];$body=['model'=>cfg('openai_model'),'input'=>[['role'=>'system','content'=>'Create an original, singable melody and playable harmony for a private notation app. Avoid copying recognizable copyrighted melodies. MIDI range 48-84, 4/4. Return structured score data only.'],['role'=>'user','content'=>"Create {$bars} bars. Style: {$style}. Instruments: ".implode(', ',$instruments).". Idea: {$prompt}"]],'text'=>['format'=>['type'=>'json_schema','name'=>'music63_composition','strict'=>true,'schema'=>$schema]]];$payload=json_encode($body);$ctx=stream_context_create(['http'=>['method'=>'POST','timeout'=>60,'ignore_errors'=>true,'header'=>"Authorization: Bearer {$key}\r\nContent-Type: application/json\r\n",'content'=>$payload]]);$raw=@file_get_contents('https://api.openai.com/v1/responses',false,$ctx);$code=0;foreach(($http_response_header??[]) as $h)if(preg_match('/^HTTP\/\S+\s+(\d+)/',$h,$m))$code=(int)$m[1];if($raw===false||$code<200||$code>=300)out(['ok'=>false,'error'=>'AI request failed. HTTP '.$code],502);$resp=json_decode($raw,true);$txt='';foreach(($resp['output']??[]) as $it)foreach(($it['content']??[]) as $c)if(($c['type']??'')==='output_text')$txt.=(string)($c['text']??'');$comp=json_decode($txt,true);if(!is_array($comp))out(['ok'=>false,'error'=>'Unexpected AI score format.'],502);out(['ok'=>true,'composition'=>$comp]);
default:out(['ok'=>false,'error'=>'Unknown action.'],404);
}
