<?php
declare(strict_types=1);
$config=require __DIR__.'/../config.php';
define('MUSIC63_ROOT',dirname(__DIR__)); define('MUSIC63_STORAGE',$config['storage_dir']);
function cfg(?string $k=null){global $config;return $k===null?$config:($config[$k]??null);} 
function headers_secure(){header('X-Content-Type-Options: nosniff');header('X-Frame-Options: DENY');header('Referrer-Policy: no-referrer');header("Permissions-Policy: camera=(), geolocation=(), microphone=(), payment=(), usb=(), midi=(self)");header("Content-Security-Policy: default-src 'self'; img-src 'self' data: blob:; media-src 'self' blob:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'");}
function session_secure(){if(session_status()===PHP_SESSION_ACTIVE)return;$secure=!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off';session_name((string)cfg('session_name'));session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>$secure,'httponly'=>true,'samesite'=>'Strict']);session_start();}
function sf($n){return MUSIC63_STORAGE.'/'.basename($n);} 
function jr($n,$fallback=[]){$p=sf($n);if(!is_file($p))return $fallback;$raw=@file_get_contents($p);$d=json_decode((string)$raw,true);return is_array($d)?$d:$fallback;}
function jw($n,$d){$p=sf($n);$tmp=$p.'.tmp.'.bin2hex(random_bytes(4));$raw=json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT);if(file_put_contents($tmp,$raw,LOCK_EX)===false)throw new RuntimeException('Storage write failed');@chmod($tmp,0660);if(!@rename($tmp,$p)){@unlink($tmp);throw new RuntimeException('Storage replace failed');}}
function ensure_storage(){@mkdir(MUSIC63_STORAGE.'/uploads',0770,true);foreach(['users.json'=>[],'songs.json'=>[],'media.json'=>[],'audit.json'=>[],'login-attempts.json'=>[],'settings.json'=>['defaultBpm'=>92,'defaultKey'=>'C','sampleLibrary'=>[],'sourceBookmarks'=>[]]] as $f=>$d)if(!is_file(sf($f)))jw($f,$d);}
function out($d,$status=200){http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function input(){return json_decode(file_get_contents('php://input')?:'{}',true)?:[];} 
function clean($v,$m=2000){$s=trim((string)$v);$s=preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/u','',$s)??'';return function_exists('mb_substr')?mb_substr($s,0,$m):substr($s,0,$m);} 
function uid($p='id'){return $p.'_'.bin2hex(random_bytes(8));}
function user(){if(empty($_SESSION['uid']))return null;foreach(jr('users.json',[]) as $u)if(($u['id']??'')===$_SESSION['uid']&&empty($u['disabled']))return ['id'=>$u['id'],'email'=>$u['email'],'name'=>$u['name']??$u['email'],'role'=>$u['role']??'user'];return null;}
function auth(){return user()?:out(['ok'=>false,'error'=>'Authentication required.'],401);} function admin(){ $u=auth(); if(($u['role']??'')!=='admin')out(['ok'=>false,'error'=>'Administrator access required.'],403); return $u; }
function csrf(){if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(24));return $_SESSION['csrf'];} function check_csrf(){if(!hash_equals((string)($_SESSION['csrf']??''),(string)($_SERVER['HTTP_X_CSRF_TOKEN']??'')))out(['ok'=>false,'error'=>'Security token expired. Refresh and try again.'],419);} 
function audit($e,$meta=[]){$r=jr('audit.json',[]);$r[]=['at'=>gmdate('c'),'user'=>user()['email']??null,'event'=>$e,'meta'=>$meta];if(count($r)>500)$r=array_slice($r,-500);jw('audit.json',$r);} 
function song_norm($s){$parts=is_array($s['parts']??null)?array_values($s['parts']):[];foreach($parts as &$p){$p=is_array($p)?$p:[];$p['id']=clean($p['id']??uid('part'),80);$p['name']=clean($p['name']??'Part',120);$p['instrument']=clean($p['instrument']??'Piano',80);$p['notes']=is_array($p['notes']??null)?array_values(array_slice($p['notes'],0,10000)):[];}unset($p);return ['id'=>clean($s['id']??uid('song'),80),'title'=>clean($s['title']??'Untitled',200),'composer'=>clean($s['composer']??'',200),'artist'=>clean($s['artist']??'',200),'lyricist'=>clean($s['lyricist']??'',200),'year'=>clean($s['year']??'',20),'language'=>clean($s['language']??'lv',20),'key'=>clean($s['key']??'C',20),'mode'=>in_array(($s['mode']??'major'),['major','minor'],true)?($s['mode']??'major'):'major','bpm'=>max(20,min(300,(int)($s['bpm']??92))),'timeSignature'=>clean($s['timeSignature']??'4/4',10),'lyrics'=>clean($s['lyrics']??'',20000),'notesText'=>clean($s['notesText']??'',8000),'sourceUrl'=>clean($s['sourceUrl']??'',2000),'rightsNote'=>clean($s['rightsNote']??'Private/personal use. Verify rights before republishing.',1000),'chords'=>is_array($s['chords']??null)?array_values(array_slice($s['chords'],0,1000)):[],'parts'=>$parts,'attachments'=>is_array($s['attachments']??null)?array_values($s['attachments']):[],'createdAt'=>clean($s['createdAt']??gmdate('c'),40),'updatedAt'=>gmdate('c')];}
headers_secure();session_secure();ensure_storage();
